# Generated by Django 6.0.8 on 2026-08-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
